import { Nunito } from "next/font/google";
import "./globals.css";
import Layout from "@/app/components/layout";

const nunito = Nunito({ subsets: ["latin"] });

export const metadata = {
  title: "Photosnap",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={nunito.className}>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
